# Site settings
url: https://jazzjackrabbit.github.io/sensint

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/blog/page:num.html"
permalink: "/blog/:year/:month/:day/:title:output_ext"
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-seo-tag]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

sass:
  sass_dir: assets/scss
  style: compressed